### ISSUE TITLE
Can we bring it back to life?

### ISSUE THREAD

**Issue by bentxt** [aryx/syncweb#1]
Hi,
I used syncweb a few years ago I was curious if I could try to build it. 

I thinks the biggest block is the external "commons" library, and I think that there is a possibility that the latest versions syncweb depends on is not available to me. There are even quite some usage and references to a Common2 library...
So I think I need some help of the original author ...
What do you think?
Ben

**Comment by bentxt** [comment]
Btw, this is the latest showstopping error after a lot of very ignorant hacking

make[2]: Nothing to be done for `all'.
/Users/ben/.opam/4.00.0/bin/ocamlc -g -dtypes -bin-annot   -I ../external/commons -thread  -c code.ml
File "code.ml", line 281, characters 12-19:
Error: This expression has type 'a list ref
       but an expression was expected of type
         string Common.stack = string list
make[2]: *** [code.cmo] Error 2
make[1]: *** [rec] Error 1
make: *** [all] Error 2

**Comment by aryx** [comment]
yes. I'm actually in the process of publishing the dependent libraries (e.g., commons) as OPAM packages (the official OCaml package manager), and make a syncweb package too, which should solve the problem.
Hopefully by next week.

**Comment by bentxt** [comment]
That's great to hear! If I can I'd like to help somehow.

**Comment by aryx** [comment]
waiting for approval of: https://github.com/ocaml/opam-repository/pull/23027

**Comment by aryx** [comment]
ok the commons library has been merged. You should be able to compile syncweb.
I've actually made a package for it! https://github.com/ocaml/opam-repository/pull/23118
Once merged, you should be able to install syncweb simply with 'opam install syncweb'
(provided you've installed opam, the OCaml package manager, before)

**Comment by aryx** [comment]
syncweb is now merged in OPAM!
you should be able to install it easily with 'opam install syncweb'.
