### ISSUE TITLE
Minor issues with the examples

### ISSUE THREAD

**Issue by bentxt** [aryx/syncweb#2]
Hi
Thank you very much for putting syncweb on opam.

There is a minor issue when you arrive as a new user of syncweb and try to follow the example instructions in the README and try to replicate the commands containing demo.ml.nw

I always got errors until I deleted the corresponding demo.ml file and generated it from scratch. I think it didn't contain the infile unison annotations (or whatever you call then.

**Comment by aryx** [comment]
oh ok. Maybe we should delete it from the repo.
