### ISSUE TITLE
build error (dllalcotest_stubs.so)

### ISSUE THREAD

**Issue by bentxt** [aryx/syncweb#4]
As far as I understand there is a new build system for syncweb. I must say I miss the `configure` script, it is still mentioned in the install.txt file. But new it looks like dune is the build system, so I try

```
dune build
File "_none_", line 1:
Error: I/O error: dllalcotest_stubs.so: No such file or directory
```

I think alcotest is installed

```
opam list | grep alcotest
alcotest              1.6.0       Alcotest is a lightweight and colourful test framework
```

**Comment by aryx** [comment]
did you do eval $(opam env) before?

**Comment by aryx** [comment]
On which machine and OS are you?

**Comment by aryx** [comment]
I've updated install.txt
you should try
make setup
make
make install

**Comment by aryx** [comment]
This requires first to follow the instruction to install and setup opam and ocaml at https://opam.ocaml.org/doc/Install.html

**Comment by bentxt** [comment]
> eval $(opam env)

Ahh yes, I always forget that one ...

> On which machine and OS are you?

Macos Ventura 13.1 (22C65)
```
opam --version
2.1.4

ocamlc -version
5.0.0

dune --version
3.6.1
```

Unfortunately I still have some issues, maybe there is something wrong with my setup, so the 'install' step is not working

```
sudo make install
dune install
Error: The mandir installation directory is unknown.
Hint: It could be specified with --mandir
make: *** [install] Error 1
```

I have the usual local directories of course like  `/usr/local//share/man` or `~/.opam/default/man` , but I have to define all the the switches in order to make the 'install' step work:

```
sudo dune install --mandir=$HOME/local/test --docdir=$HOME/local/test --etcdir=$HOME/local/test --datadir=$HOME/local/test --sbindir=$HOME/local/test --bindir=$HOME/local/test --libexecdir=$HOME/local/test --libdir=$HOME/local/test
```

To get this result: 
```
ls ~/local/test/syncweb/
META          dune-package  opam
```

**Comment by aryx** [comment]
Did you try to install other opam packages with binaries? For example try to install ocamlformat.
I never saw those errors but seems more like you have a problem with OPAM than syncweb.

**Comment by bentxt** [comment]
> For example try to install ocamlformat

I tried that and it helped to make me aware of the (a little stupid) error. Out of habit 
```
sudo make install
```

`sudo` was responsible for all the trouble ...
